import React, { useState, useEffect } from 'react';
import { useApp } from '../context/AppContext';
import { api } from '../services/api';
import { currentUser } from '../data/currentUser';
import { TestAttemptResult } from '../types';
import { 
  BarChart3, 
  TrendingUp, 
  Clock, 
  Target, 
  Sparkles, 
  Award, 
  AlertTriangle, 
  CheckCircle2, 
  Brain, 
  Zap, 
  RefreshCw 
} from 'lucide-react';

export const AnalyticsPage: React.FC = () => {
  const { user, showToast } = useApp();
  const [attempts, setAttempts] = useState<TestAttemptResult[]>([]);
  const [loading, setLoading] = useState(true);
  const [aiAnalysis, setAiAnalysis] = useState<any>(null);
  const [analyzingWithAI, setAnalyzingWithAI] = useState(false);

  useEffect(() => {
    const loadAttempts = async () => {
      try {
        const list = await api.getTestAttempts();
        setAttempts(list);
      } catch (err) {
        console.error('Failed to load attempts:', err);
      } finally {
        setLoading(false);
      }
    };
    loadAttempts();
  }, []);

  const handleGenerateAIAnalysis = async () => {
    setAnalyzingWithAI(true);
    try {
      const stats = {
        studentName: user?.name || currentUser.name,
        totalMockTests: user?.mockTestsCompleted || attempts.length || 4,
        averageScore: user?.averageScore || 142.5,
        accuracy: user?.accuracy || 84.1,
        weakTopics: ['Compound Interest', 'Circle Geometry Theorems', 'Indian Polity (Articles 32-51)'],
        strongTopics: ['Coding-Decoding', 'English Vocabulary & Idioms', 'Percentage & Profit-Loss'],
        recentTestScores: attempts.map(a => a.score)
      };

      const result = await api.analyzePerformance(stats);
      setAiAnalysis(result);
      showToast({
        type: 'success',
        title: 'AI Analysis Complete',
        message: 'Personalized strategy generated by Gemini 3.8 Flash.'
      });
    } catch (err) {
      showToast({ type: 'error', message: 'Failed to generate AI analysis' });
    } finally {
      setAnalyzingWithAI(false);
    }
  };

  const scores = attempts.map(a => a.score);
  const maxScorePossible = 200;

  return (
    <div className="space-y-6 sm:space-y-8 py-2">
      
      {/* Page Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-600 dark:text-indigo-400">
            <span>Diagnostic Performance Intelligence</span>
            <span>·</span>
            <span className="text-slate-500 dark:text-slate-400 font-semibold">{user?.name || currentUser.name}</span>
          </div>
          <h1 className="text-2xl sm:text-3xl font-bold text-slate-900 dark:text-white mt-1">
            Performance Analytics & AI Insights
          </h1>
          <p className="text-xs sm:text-sm text-slate-500 dark:text-slate-400 mt-1">
            Comprehensive diagnostic trends, sectional strengths, and targeted AI revision roadmaps for {user?.name || currentUser.name}.
          </p>
        </div>

        <button
          onClick={handleGenerateAIAnalysis}
          disabled={analyzingWithAI}
          className="py-2.5 px-4 rounded-xl bg-gradient-to-r from-indigo-600 to-blue-600 hover:from-indigo-500 hover:to-blue-500 text-white text-xs font-bold shadow-md shadow-indigo-600/20 transition-all flex items-center gap-2 cursor-pointer shrink-0"
        >
          {analyzingWithAI ? (
            <>
              <RefreshCw className="w-3.5 h-3.5 animate-spin" />
              <span>Analyzing with Gemini AI...</span>
            </>
          ) : (
            <>
              <Sparkles className="w-3.5 h-3.5 text-amber-300" />
              <span>Run AI Performance Analysis</span>
            </>
          )}
        </button>
      </div>

      {/* KPI Overview Grid */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4">
        <div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="flex items-center justify-between text-slate-400 mb-2">
            <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Avg Mock Score</span>
            <Award className="w-4 h-4 text-indigo-500" />
          </div>
          <div className="text-2xl font-black text-slate-900 dark:text-white">
            {user?.averageScore || 142.5} <span className="text-xs font-normal text-slate-400">/ 200</span>
          </div>
          <div className="text-[11px] text-emerald-600 dark:text-emerald-400 font-medium mt-1">
            +14 pts from initial mock
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="flex items-center justify-between text-slate-400 mb-2">
            <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Overall Accuracy</span>
            <TrendingUp className="w-4 h-4 text-emerald-500" />
          </div>
          <div className="text-2xl font-black text-emerald-600 dark:text-emerald-400">
            {user?.accuracy || 84.1}%
          </div>
          <div className="text-[11px] text-slate-400 mt-1">
            Top 5% cutoff benchmark: 88%
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="flex items-center justify-between text-slate-400 mb-2">
            <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Time / Question</span>
            <Clock className="w-4 h-4 text-sky-500" />
          </div>
          <div className="text-2xl font-black text-slate-900 dark:text-white">
            44.2 <span className="text-xs font-normal text-slate-400">sec</span>
          </div>
          <div className="text-[11px] text-sky-600 dark:text-sky-400 font-medium mt-1">
            Exam target: &le; 50 sec
          </div>
        </div>

        <div className="p-4 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs">
          <div className="flex items-center justify-between text-slate-400 mb-2">
            <span className="text-[11px] font-semibold uppercase tracking-wider text-slate-500">Mocks Completed</span>
            <Target className="w-4 h-4 text-purple-500" />
          </div>
          <div className="text-2xl font-black text-slate-900 dark:text-white">
            {user?.mockTestsCompleted || 4}
          </div>
          <div className="text-[11px] text-purple-600 dark:text-purple-400 font-medium mt-1">
            Active Tier-1 Series
          </div>
        </div>
      </div>

      {/* AI Performance Analysis Section (Rendered when generated or default) */}
      {aiAnalysis && (
        <div className="p-6 sm:p-8 rounded-3xl bg-gradient-to-br from-indigo-950 via-slate-900 to-indigo-900 text-white border border-indigo-700/60 shadow-xl space-y-6 animate-in fade-in slide-in-from-top-3">
          <div className="flex items-center gap-2.5">
            <div className="w-9 h-9 rounded-xl bg-amber-400/20 border border-amber-300/30 flex items-center justify-center text-amber-300">
              <Brain className="w-5 h-5" />
            </div>
            <div>
              <div className="text-xs font-bold uppercase tracking-wider text-indigo-300">
                AI Diagnostic Report for {user?.name || currentUser.name} (Gemini 3.8 Flash)
              </div>
              <h2 className="text-lg font-bold">Personalized Strategic Revision Plan</h2>
            </div>
          </div>

          <div className="p-4 rounded-2xl bg-white/10 backdrop-blur-md text-xs sm:text-sm text-indigo-100 leading-relaxed">
            {aiAnalysis.executiveSummary}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            
            {/* Weak Areas to Target */}
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-2">
              <div className="flex items-center gap-2 text-rose-300 font-bold text-xs uppercase tracking-wider">
                <AlertTriangle className="w-4 h-4" />
                <span>Critical Weak Topics (High Priority)</span>
              </div>
              <ul className="space-y-1.5 text-xs text-slate-300">
                {aiAnalysis.criticalGaps?.map((gap: string, i: number) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-rose-400 font-bold">·</span>
                    <span>{gap}</span>
                  </li>
                ))}
              </ul>
            </div>

            {/* Daily Practice Strategy */}
            <div className="p-4 rounded-2xl bg-white/5 border border-white/10 space-y-2">
              <div className="flex items-center gap-2 text-emerald-300 font-bold text-xs uppercase tracking-wider">
                <Zap className="w-4 h-4" />
                <span>Recommended Daily Strategy</span>
              </div>
              <ul className="space-y-1.5 text-xs text-slate-300">
                {aiAnalysis.actionPlanDaily?.map((plan: string, i: number) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-emerald-400 font-bold">✓</span>
                    <span>{plan}</span>
                  </li>
                ))}
              </ul>
            </div>

          </div>
        </div>
      )}

      {/* Visual Analytics Grid: SVG Charts */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        
        {/* Score Progression Trend Chart */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider">
              Mock Test Score Progression (Last 5 Mocks)
            </h3>
            <span className="text-[11px] font-semibold text-indigo-600 dark:text-indigo-400">
              Tier-1 Max: 200 Marks
            </span>
          </div>

          <div className="h-52 w-full flex items-end justify-between gap-3 pt-6 pb-2 px-4 bg-slate-50 dark:bg-slate-800/40 rounded-xl border border-slate-100 dark:border-slate-800">
            {[
              { mock: 'Mock #1', score: 128 },
              { mock: 'Mock #2', score: 135 },
              { mock: 'Mock #3', score: 142 },
              { mock: 'Mock #4', score: 146 },
              { mock: 'Live #01', score: 154 }
            ].map((bar, idx) => {
              const heightPct = Math.round((bar.score / maxScorePossible) * 100);
              return (
                <div key={idx} className="flex-1 flex flex-col items-center gap-2 h-full justify-end">
                  <span className="text-[11px] font-bold text-indigo-600 dark:text-indigo-400">
                    {bar.score}
                  </span>
                  <div
                    className="w-full max-w-[40px] bg-gradient-to-t from-indigo-700 to-indigo-500 rounded-t-lg transition-all duration-500 hover:brightness-110"
                    style={{ height: `${heightPct}%` }}
                  />
                  <span className="text-[10px] text-slate-400 font-medium truncate w-full text-center">
                    {bar.mock}
                  </span>
                </div>
              );
            })}
          </div>
        </div>

        {/* Sectional Accuracy Radar / Bar Breakdown */}
        <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider">
              Subject Accuracy & Readiness Index
            </h3>
            <span className="text-[11px] text-slate-400">Benchmarked against cutoffs</span>
          </div>

          <div className="space-y-4 pt-2">
            {[
              { name: 'Quantitative Aptitude', acc: 81, color: 'bg-emerald-500', note: 'Strong in Arithmetic, Algebra needs practice' },
              { name: 'General Intelligence & Reasoning', acc: 92, color: 'bg-indigo-600', note: 'Fast & Highly Accurate' },
              { name: 'English Comprehension', acc: 88, color: 'bg-sky-500', note: 'Consistent Grammar & Vocab' },
              { name: 'General Awareness (Static GK + CA)', acc: 74, color: 'bg-amber-500', note: 'Needs Modern History & Polity Revision' }
            ].map((sec, idx) => (
              <div key={idx} className="space-y-1.5">
                <div className="flex justify-between text-xs">
                  <span className="font-bold text-slate-800 dark:text-slate-200">{sec.name}</span>
                  <span className="font-bold text-indigo-600 dark:text-indigo-400">{sec.acc}%</span>
                </div>
                <div className="w-full h-2 rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden">
                  <div
                    className={`h-full ${sec.color} rounded-full transition-all duration-500`}
                    style={{ width: `${sec.acc}%` }}
                  />
                </div>
                <div className="text-[10px] text-slate-400">{sec.note}</div>
              </div>
            ))}
          </div>
        </div>

      </div>

      {/* Mock Test History Table */}
      <div className="p-6 rounded-2xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-xs space-y-4">
        <h3 className="text-xs font-bold text-slate-900 dark:text-white uppercase tracking-wider">
          Mock Test Attempt History
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-800 text-slate-400 text-[11px]">
                <th className="pb-3 font-semibold">Test Name</th>
                <th className="pb-3 font-semibold">Date</th>
                <th className="pb-3 font-semibold">Score</th>
                <th className="pb-3 font-semibold">Accuracy</th>
                <th className="pb-3 font-semibold">Attempted</th>
                <th className="pb-3 font-semibold">Time Spent</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {attempts.length === 0 ? (
                <tr>
                  <td colSpan={6} className="py-6 text-center text-slate-400">
                    No mock tests taken yet. Attempt your first test in the Mock Test Series.
                  </td>
                </tr>
              ) : (
                attempts.map(att => (
                  <tr key={att.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/40">
                    <td className="py-3 font-bold text-slate-900 dark:text-white">{att.testTitle}</td>
                    <td className="py-3 text-slate-400">{new Date(att.completedAt).toLocaleDateString()}</td>
                    <td className="py-3 font-black text-indigo-600 dark:text-indigo-400">
                      {att.score} / {att.maxScore}
                    </td>
                    <td className="py-3 font-semibold text-emerald-600 dark:text-emerald-400">
                      {att.accuracyPercentage}%
                    </td>
                    <td className="py-3 text-slate-500">
                      {att.attemptedQuestions} / {att.totalQuestions}
                    </td>
                    <td className="py-3 text-slate-500">
                      {Math.round(att.totalTimeSpentSeconds / 60)} mins
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};
